export const mockZones = [
  {
    zoneId: 'zone-1',
    zone: 'Dwarka',
    microMarket: 'Dwarka Sector 8-9',
    location: {
      latitude: 28.592,
      longitude: 77.0455,
      address: 'Dwarka, Delhi',
    },
    overallScore: 85,
    category: 'EMERGING',
    municipalWeight: 82,
    marketWeight: 88,
    priceVelocityWeight: 85,
    forecastedROI: 14.5,
    confidenceLevel: 92,
  },
  {
    zoneId: 'zone-2',
    zone: 'Gurugram',
    microMarket: 'Golf Course Road',
    location: {
      latitude: 28.4595,
      longitude: 77.1335,
      address: 'Golf Course Road, Gurugram',
    },
    overallScore: 78,
    category: 'GROWING',
    municipalWeight: 75,
    marketWeight: 80,
    priceVelocityWeight: 79,
    forecastedROI: 11.2,
    confidenceLevel: 88,
  },
  {
    zoneId: 'zone-3',
    zone: 'Noida',
    microMarket: 'Sector 62',
    location: {
      latitude: 28.6139,
      longitude: 77.3934,
      address: 'Sector 62, Noida',
    },
    overallScore: 62,
    category: 'GROWING',
    municipalWeight: 65,
    marketWeight: 60,
    priceVelocityWeight: 61,
    forecastedROI: 8.3,
    confidenceLevel: 82,
  },
  {
    zoneId: 'zone-4',
    zone: 'Pune',
    microMarket: 'Hinjewadi',
    location: {
      latitude: 18.591,
      longitude: 73.7997,
      address: 'Hinjewadi, Pune',
    },
    overallScore: 88,
    category: 'EMERGING',
    municipalWeight: 90,
    marketWeight: 85,
    priceVelocityWeight: 89,
    forecastedROI: 15.8,
    confidenceLevel: 94,
  },
  {
    zoneId: 'zone-5',
    zone: 'Bengaluru',
    microMarket: 'Sarjapur Road',
    location: {
      latitude: 12.9352,
      longitude: 77.6245,
      address: 'Sarjapur Road, Bengaluru',
    },
    overallScore: 72,
    category: 'GROWING',
    municipalWeight: 70,
    marketWeight: 75,
    priceVelocityWeight: 71,
    forecastedROI: 10.1,
    confidenceLevel: 85,
  },
  {
    zoneId: 'zone-6',
    zone: 'Mumbai',
    microMarket: 'Bandra East',
    location: {
      latitude: 19.0596,
      longitude: 72.8295,
      address: 'Bandra East, Mumbai',
    },
    overallScore: 55,
    category: 'MATURE',
    municipalWeight: 52,
    marketWeight: 58,
    priceVelocityWeight: 55,
    forecastedROI: 6.5,
    confidenceLevel: 80,
  },
];

export const mockMetrics = {
  totalZonesAnalyzed: 42,
  emergingZones: 8,
  growingZones: 18,
  matureZones: 12,
  decliningZones: 4,
  averageGrowthScore: 68.5,
  totalMunicipalProjects: 156,
  totalListings: 3842,
  lastUpdateDate: new Date().toISOString(),
};

export const mockMunicipalProjects = [
  {
    id: 'project-1',
    projectName: 'Delhi Metro Purple Line Extension',
    category: 'METRO',
    location: {
      latitude: 28.592,
      longitude: 77.0455,
      zone: 'Dwarka',
    },
    description: 'Extension of metro line to new residential zones',
    announcementDate: '2024-01-15',
    estimatedCompletionDate: '2026-06-30',
    investmentAmount: 450,
    status: 'UNDER_CONSTRUCTION',
    url: 'https://example.com/project/1',
  },
  {
    id: 'project-2',
    projectName: 'Expressway Expansion Project',
    category: 'ROAD',
    location: {
      latitude: 28.4595,
      longitude: 77.1335,
      zone: 'Gurugram',
    },
    description: 'Expansion of expressway capacity',
    announcementDate: '2024-02-20',
    estimatedCompletionDate: '2026-03-31',
    investmentAmount: 300,
    status: 'TENDER',
    url: 'https://example.com/project/2',
  },
];

export const mockListings = [
  {
    id: 'listing-1',
    location: {
      latitude: 28.592,
      longitude: 77.0455,
      zone: 'Dwarka',
    },
    propertyType: 'RESIDENTIAL',
    stage: 'READY_TO_MOVE',
    pricePerSqft: 8500,
    totalPrice: 4250000,
    area: 500,
    rentAmount: 35000,
    ROI: 9.88,
    listingDate: '2024-01-10',
    daysOnMarket: 45,
    developerName: 'ABC Developers',
    completionYear: 2024,
  },
  {
    id: 'listing-2',
    location: {
      latitude: 28.4595,
      longitude: 77.1335,
      zone: 'Gurugram',
    },
    propertyType: 'RESIDENTIAL',
    stage: 'UNDER_CONSTRUCTION',
    pricePerSqft: 7800,
    totalPrice: 3900000,
    area: 500,
    rentAmount: 32000,
    ROI: 9.83,
    listingDate: '2024-02-05',
    daysOnMarket: 30,
    developerName: 'XYZ Construction',
    completionYear: 2025,
  },
];

export const mockTrendData = [
  {
    zoneId: 'zone-1',
    zone: 'Dwarka',
    rentalYield: 9.88,
    sellPrice: 8500,
    rentPrice: 1167,
    yieldGap: 1.38,
    opportunity: 'UNDERVALUED',
    forecastedAppreciation: 12.5,
  },
  {
    zoneId: 'zone-2',
    zone: 'Gurugram',
    rentalYield: 8.2,
    sellPrice: 7800,
    rentPrice: 1067,
    yieldGap: 0.65,
    opportunity: 'FAIRLY_VALUED',
    forecastedAppreciation: 9.8,
  },
];
